services:
  - type: web
    name: ismartshop-backend
    env: node
    region: oregon
    repo: ismartshopdatabase
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: FRONTEND_URL
        value: "https://webdev-it.github.io/ismartshop"
      - key: SESSION_SECRET
        value: "__REPLACE_ME__"

databases:
  - name: ismartshop-db
    databaseName: ismartshop
    plan: starter
    region: oregon
